import React from "react";
import Head from "next/head";
import { Flex } from "@chakra-ui/react";
import Header from "../Header";
import Footer from "../Footer";

type Props = {
  title?: string;
};

const Layout: React.FC<Props> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>
          {title ? title : "Desapega Livro - Seu lugar de doar livros!"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Aladin&family=Dancing+Script:wght@400;500;600;700&family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
        <link href="https://www.dafontfree.net/embed/bXYtYm9saS1yZWd1bGFyJmRhdGEvNDkvbS8zODM0My9tdmJvbGkudHRm" rel="stylesheet" type="text/css"/>
      </Head>

      <Flex direction="column" minH="100vh" w="100%" bgColor="#F5F0EE">
        <Header />
        {children}
        <Footer />
      </Flex>
    </>
  );
};

export default Layout;
